# Generated by Django 4.2.30 on 2026-06-19 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_backlog_activity_sync'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backlogactivitysync',
            options={'verbose_name': 'Backlog Activity Sync', 'verbose_name_plural': 'Backlog Activity Syncs'},
        ),
        migrations.AlterModelOptions(
            name='backlogcommentsync',
            options={'verbose_name': 'Backlog Comment Sync', 'verbose_name_plural': 'Backlog Comment Syncs'},
        ),
        migrations.AlterModelOptions(
            name='backlogissuesync',
            options={'verbose_name': 'Backlog Issue Sync', 'verbose_name_plural': 'Backlog Issue Syncs'},
        ),
        migrations.AlterModelOptions(
            name='backlogprojectsync',
            options={'verbose_name': 'Backlog Project Sync', 'verbose_name_plural': 'Backlog Project Syncs'},
        ),
    ]
