ARG DOCKER_REGISTRY=100.98.98.98:5000
ARG DOCKER_IMAGE_PREFIX=bitaplane
FROM ${DOCKER_REGISTRY}/${DOCKER_IMAGE_PREFIX}/caddy-builder:2.10.0 AS caddy-builder

FROM caddy:2.10.0-alpine

RUN apk add --no-cache nss-tools bash curl

COPY --from=caddy-builder /usr/bin/caddy /usr/bin/caddy

COPY Caddyfile.ce /etc/caddy/Caddyfile