ARG DOCKER_REGISTRY=100.98.98.98:5000
ARG DOCKER_IMAGE_PREFIX=bitaplane
FROM ${DOCKER_REGISTRY}/${DOCKER_IMAGE_PREFIX}/python-base:3.12.10-alpine

ENV INSTANCE_CHANGELOG_URL=https://sites.plane.so/pages/691ef037bcfe416a902e48cb55f59891/

WORKDIR /code
COPY manage.py manage.py
COPY plane plane/
COPY templates templates/
COPY package.json package.json

COPY ./bin ./bin/

RUN mkdir -p /code/plane/logs
RUN chmod +x ./bin/*
RUN chmod -R 777 /code

# Expose container port and run entry point script
EXPOSE 8000

CMD ["./bin/docker-entrypoint-api.sh"]